component: shipping
app_path: /app
schema: mysql
schema_files:
  - schema
  - master-data
  - app-user

secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/shipping token={{vault_token}} url=https://vault.naifah.online:8200 validate_certs=False')}}"