
- name: MYSQL INSTALL
  ansible.builtin.dnf:
    name: mysql-server

- name:  MYSQL ENABLE
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.MYSQL_ROOT_PASSWORD }}
