- name: Run dispat container
  containers.podman.podman_container::
    name: dispatch
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/dispatch
    state: started
    ports:
        - "8080:8080"
    env:
     AMQP_HOST={{ secrets.AMQP_HOST }}
     AMQP_USER={{ secrets.AMQP_USER }}
     AMQP_PASS={{ secrerts.AMQP_PASS }}