component: catalogue
app_path: /app
schema: mongo
schema_files:
  - master-data

secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/catalogue token={{vault_token}} url=https://vault.naifah.online:8200 validate_certs=False')}}"


